### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Div685** [jaspreet-singh-sahota/netflix-clone-react-capstone-project#2]
Congratulations, Netflix clone looks so amazing I was so excited to see a live version of your project but somehow your Live Link (Heroku) on your readme didn't work. But from the screenshot, it looks amazing.

**Comment by PurushothamanSrikanth** [comment]
> Congratulations, Netflix clone looks so amazing I was so excited to see a live version of your project but somehow your Live Link (Heroku) on your readme didn't work. But from the screenshot, it looks amazing.

@Div685 The link which you were talking about is working fine now (for me). 
LINK- https://jassi-netflix-clone.herokuapp.com/

**Comment by Div685** [comment]
yeah I just checked, the link is working now and the Netflix clone is just too good
